### ISSUE TITLE
libhiredis.so.0.13: cannot open shared object file

### ISSUE THREAD

**Issue by SanjanaSridhar** [pg-redis-fdw/redis_fdw#10]
Hello,

I'm just getting started with integrating Redis and postgresql. I have hiredis - the C client library installed and also the redis fdw. When I try to create the extension though I get the following error:

ERROR:  could not load library "/usr/lib/postgresql/9.3/lib/redis_fdw.so": libhiredis.so.0.13: cannot open shared object file: No such file or directory

libhiredis.so.0.13 is currently in the directory /usr/local/lib.

Any help will be greatly appreciated. Thank you

**Comment by adunstan** [comment]
You might need to set LD_LIBRARY_PATH for the running postgres, or add the directory to /etc/ld.so.conf, or something similar.
