### ISSUE TITLE
What about redis_fdw for Windows?

### ISSUE THREAD

**Issue by win32nipuh** [pg-redis-fdw/redis_fdw#11]
Does exist redis_fdw for PostgreSQL x64 windows ?
Or how I can build it in VS2013?

Thnx

**Comment by adunstan** [comment]
I have never tried it. It should be possible to build if you have the hiredis libraries  and headers installed. The simplest way is probably to put the fdw source in the postgresql contrib directory and then do a normal postgresql build. The build system should pick up any module in contrib and try to build it. You might have to add in config settings for the locations of the hiredis headers and libraries.
