### ISSUE TITLE
make: *** No rule to make target `make'.  Stop

### ISSUE THREAD

**Issue by rizvanhaider** [pg-redis-fdw/redis_fdw#12]
*make: *** No rule to make target `make'.  Stop*
I encountered the above problem while building the path using the following commands.
**PATH=/usr/share/postgresql/9.4/:$PATH make USE_PGXS=1 make**

I also tried the following commands but I faced the same error.
**PATH=/usr/lib/postgresql/9.4/bin/:$PATH make USE_PGXS=1 make**

**Comment by adunstan** [comment]
Your command line is wrong. You should not have "make" at the end of it.
