### ISSUE TITLE
Cache expire?

### ISSUE THREAD

**Issue by gspiegelberg** [pg-redis-fdw/redis_fdw#13]
Is there a way to set keys to expire in redis via this FDW?

**Comment by adunstan** [comment]
No, they are pretty much treated as persistent values.  Its would be possible to set a timeout as a table option and implement that fairly easily, but I'm sure how much value that would be. There is a postgres wrapper around the hiredis API that would let you expire keys. It can be cloned from https://bitbucket.org/IVC-Inc/redis_wrapper.git
