### ISSUE TITLE
running on rds postgres

### ISSUE THREAD

**Issue by fortm** [pg-redis-fdw/redis_fdw#19]
Running create extension redis_fdw gives below error. Currently is there any alternative way to create foreign data wrapper for redis and achieve similar goals as this project on RDS ?

`Extension "redis_fdw" is not supported by Amazon RDS`

Thanks

**Comment by adunstan** [comment]
I don't believe so. But Heroku does: https://devcenter.heroku.com/articles/heroku-postgres-extensions-postgis-full-text-search

**Comment by braco** [comment]
Looks like they just support postgres_fdw now?

Was curious if there was a way to get this running on RDS but there doesn't seem to be.
