### ISSUE TITLE
Performance problem

### ISSUE THREAD

**Issue by Serob** [pg-redis-fdw/redis_fdw#20]
Is it normal that inserting a single two-column line in a redis_fdw scalar/hash table lasts much **longer** than in a regular Postgres table (in average  0.6 ms vs 0.06 ms) while ram is nearly free? Almost the same situation with reading.  I thought that read/write actions in in-memory database should take less (_or equal_)  time than in Postgres (_which is true for direct access_) . But benchmarks show opposite!
What can cause such behavior? 

My system is Ubuntu 14,  Postgres 9.3, Redis 2.8.4
RAM 3GB, 
Processor 4 core 2.3 GHz
HDD SATA2 with below average speed

**Comment by adunstan** [comment]
There is the redis connection overhead. Also, PostgreSQL also caches tables in memory (shared_buffers). So this is not necessarily surprising.
