### ISSUE TITLE
Make use of HINCRBY?

### ISSUE THREAD

**Issue by baudehlo** [pg-redis-fdw/redis_fdw#21]
Is there any way to use this to access HINCRBY? I can't find anything in the docs or tests that would reflect it.

**Comment by adunstan** [comment]
No, how would that work via a foreign data wrapper? There is a low-level redis extension also available, although it's not very maintained, but still works - see https://bitbucket.org/IVC-Inc/redis_wrapper

**Comment by baudehlo** [comment]
I didn't know if the modules got access to the sql used, in which case you might be able to see 'colname = colname + ?' statements and convert them. But I guess pg does all the sql parsing before it gets to the fdw.

**Comment by adunstan** [comment]
The whole point of Foreign Data Wrappers is not to give SQL access to the foreign API but to make the foreign data store look like SQL tables. If you want SQL access to the Redis API, use redis-wrapper - that's what it's designed for. You can use both.
