### ISSUE TITLE
question about connection pooling for the fdw

### ISSUE THREAD

**Issue by zcaudate** [pg-redis-fdw/redis_fdw#28]
I'm wondering if there is connecting pooling for redis fdw.

Also, I'd like to be able to run an EVAL call to redis with arguments (to get back a json in order to insert into a table), is there anyway to do this currently?

**Comment by adunstan** [comment]
1. there isn't any connection pooling, or even connection caching right now. We need to do caching.
2. See https://bitbucket.org/adunstan/redis_wrapper/src/master/ it might do what you need

**Comment by zcaudate** [comment]
@adunstan  thanks for the link. it is what I'm after. 

I'm curious why you didn't put the repo up on GitHub?

**Comment by adunstan** [comment]
It was originally developed for a company that uses BitBucket as their cloud git provider.  I use Github, Bitbucket and GitLab :-)

**Comment by zcaudate** [comment]
@adunstan: can I get a couple of clarifications about your library - https://github.com/zcaudate/redis_wrapper

Am I correct is understanding that:
- a single connection can open multiple redis connections
- two db connections cannot share a redis connection
- there is some sort of auto cleanup when a db connection goes down.
- the best way is to keep the db pool and create redis connections as needed.
