### ISSUE TITLE
Use SCAN rather than KEYS

### ISSUE THREAD

**Issue by cyberdelia** [pg-redis-fdw/redis_fdw#7]
There is a cursor like implementation of ``KEYS``, named ``SCAN``, this might allow for better performances, see: http://redis.io/commands/scan

**Comment by fnando** [comment]
:+1:

**Comment by adunstan** [comment]
Seems reasonable, although I don't currently have time to work on it.

**Comment by adunstan** [comment]
See commit 8a6ccfcd747275cc453fb7d1aba7e9defad0b26e
